In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [5]:
print(torch.__version__)

2.5.1+cu124


#### Basically creating a tensor, but why are we calling it a scalar?

In [6]:
#scalar
scalar =torch.tensor(7)

In [7]:
scalar

tensor(7)

In [8]:
# so it has 0 dimension , which makes sense
scalar.ndim

0

In [9]:
#getting back int form python data types 
scalar.item()

7

### Vectors

In [10]:
vector=torch.tensor([1,2,3])

In [11]:
vector

tensor([1, 2, 3])

In [12]:
vector.ndim

1

### Matrix

In [13]:
matrix=torch.tensor([[1,2,3],[4,5,6]])

In [14]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
matrix.ndim

2

In [16]:
matrix[0,2]

tensor(3)

### 3D 

In [17]:
tensors=torch.tensor([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [18]:
tensors

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [19]:
tensors.shape

torch.Size([2, 2, 3])

In [20]:
tensors[0,0]

tensor([1, 2, 3])

# Day-2

### Random tensor

Random tensors are important because the way many neural networks learn is they have random tensor at the beginning and then those numbers are updated ,

In [21]:
#create a random tensor of size(4,5)
random_tensor=torch.rand(4,5)

In [22]:
random_tensor

tensor([[0.9525, 0.5990, 0.5369, 0.0340, 0.7408],
        [0.2241, 0.2574, 0.0703, 0.1525, 0.0930],
        [0.8796, 0.7477, 0.2990, 0.0600, 0.1459],
        [0.0154, 0.9468, 0.6462, 0.9703, 0.4566]])

In [23]:
#creating a random image tensor
random_tensor_image=torch.rand(224,224,3) #height , width and color channel
random_tensor_image.ndim

3

In [24]:
#tensors with binary bits
zero_tensor=torch.zeros(4,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
np.dot(zero_tensor,random_tensor)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [26]:
zero_tensor.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### It seems that the default data type for tensor is float32

#### Creating zeros tensor which has shape of exisiting tensor

In [28]:
zero_like=torch.zeros_like(random_tensor)
zero_like.shape

torch.Size([4, 5])

In [29]:
random_tensor.shape


torch.Size([4, 5])

#### arange , start, stop, step (kind of like python built in range)


In [30]:
one_to_somewhere=torch.arange(1,100,2)
one_to_somewhere

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [31]:
one_to_somewhere=torch.arange(1,100,1/2)
one_to_somewhere


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000, 16.0000, 16.5000,
        17.0000, 17.5000, 18.0000, 18.5000, 19.0000, 19.5000, 20.0000, 20.5000,
        21.0000, 21.5000, 22.0000, 22.5000, 23.0000, 23.5000, 24.0000, 24.5000,
        25.0000, 25.5000, 26.0000, 26.5000, 27.0000, 27.5000, 28.0000, 28.5000,
        29.0000, 29.5000, 30.0000, 30.5000, 31.0000, 31.5000, 32.0000, 32.5000,
        33.0000, 33.5000, 34.0000, 34.5000, 35.0000, 35.5000, 36.0000, 36.5000,
        37.0000, 37.5000, 38.0000, 38.5000, 39.0000, 39.5000, 40.0000, 40.5000,
        41.0000, 41.5000, 42.0000, 42.5000, 43.0000, 43.5000, 44.0000, 44.5000,
        45.0000, 45.5000, 46.0000, 46.5000, 47.0000, 47.5000, 48.0000, 48.5000,
        49.0000, 49.5000, 50.0000, 50.50

#### So basically we can also put fraction in step

#### Tensor datatypes

In [32]:
#default is float32 for rand 
float_32_tensor=torch.arange(1,10,0.5)
float_32_tensor.dtype

torch.float32

In [33]:
int_64_tensor=torch.tensor([1,2,3.5],dtype=int)
int_64_tensor

tensor([1, 2, 3])

#### some more params passed to tensor

In [34]:
float_32_tensor=torch.tensor([3.0,4.0,5.0],
                             dtype=None, # so that we don't have problem doing operation with float 16
                             device="cuda",  # be careful, tensor on cpu and gpu does not mix well
                             requires_grad=False #no track gradient, idk what that means yet
                             ,)
float_32_tensor

tensor([3., 4., 5.], device='cuda:0')

### Conversion of data types

In [35]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

##### let see what happens if we multiply two different float with differnt bit

In [36]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 25.], device='cuda:0')

##### let's multiply float and integer

In [37]:
int_16_tensor=float_16_tensor.type(torch.int16)
int_16_tensor.dtype

torch.int16

In [38]:
int_16_tensor*float_16_tensor

tensor([ 9., 16., 25.], device='cuda:0', dtype=torch.float16)

##### Python allows this

#### Errors I will get in tensor data 
-  ##### Tensor not right data type (find the data type , use tensor.dtype)
-  ##### Tensor not right shape (get shape from tensor, use tensor.shape)
-  ##### Tensor not right device (use tensor.device)


#### see this if you get the above errors

In [39]:
debug_tensor=torch.rand(3,5)

debug_tensor

tensor([[0.4795, 0.3756, 0.1534, 0.3544, 0.5959],
        [0.8278, 0.1998, 0.2545, 0.9696, 0.3852],
        [0.4753, 0.6460, 0.5015, 0.0998, 0.0585]])

In [40]:
print(f'the shape of tensor is {debug_tensor.shape}')
print(f'the datatypes of tensor is {debug_tensor.dtype}')
print(f'the device of tensor is {debug_tensor.device}')


the shape of tensor is torch.Size([3, 5])
the datatypes of tensor is torch.float32
the device of tensor is cpu


#### Manipulating Tensor (tensor operations)

#### 1: Addition (it must have same shape)

In [41]:
debug_tensor+debug_tensor

tensor([[0.9589, 0.7512, 0.3068, 0.7088, 1.1918],
        [1.6556, 0.3995, 0.5090, 1.9391, 0.7703],
        [0.9506, 1.2919, 1.0030, 0.1997, 0.1171]])

In [42]:
debug_tensor +10

tensor([[10.4795, 10.3756, 10.1534, 10.3544, 10.5959],
        [10.8278, 10.1998, 10.2545, 10.9696, 10.3852],
        [10.4753, 10.6460, 10.5015, 10.0998, 10.0585]])

#### 2: Subtraction (It must have same shape)

In [43]:
debug_tensor -10

tensor([[-9.5205, -9.6244, -9.8466, -9.6456, -9.4041],
        [-9.1722, -9.8002, -9.7455, -9.0304, -9.6148],
        [-9.5247, -9.3540, -9.4985, -9.9002, -9.9415]])

In [44]:
debug_tensor - debug_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

#### 3: Multiplication (two tensor must have cols and row same for first and second tensor in order)

In [45]:
debug_tensor.shape, random_tensor.shape

(torch.Size([3, 5]), torch.Size([4, 5]))

In [46]:
## this should not work
debug_tensor*random_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [48]:
transpose_random_tensor=np.transpose(random_tensor)
transpose_random_tensor.shape

torch.Size([5, 4])

In [49]:
## now we should be able to multiply debug tensor with transpose_random_tensor
debug_tensor*transpose_random_tensor

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

### OH NO


In [50]:
debug_tensor.shape,transpose_random_tensor.shape


(torch.Size([3, 5]), torch.Size([5, 4]))

In [98]:
debug_tensor,transpose_random_tensor

(tensor([[0.4795, 0.3756, 0.1534, 0.3544, 0.5959],
         [0.8278, 0.1998, 0.2545, 0.9696, 0.3852],
         [0.4753, 0.6460, 0.5015, 0.0998, 0.0585]]),
 tensor([[0.9525, 0.2241, 0.8796, 0.0154],
         [0.5990, 0.2574, 0.7477, 0.9468],
         [0.5369, 0.0703, 0.2990, 0.6462],
         [0.0340, 0.1525, 0.0600, 0.9703],
         [0.7408, 0.0930, 0.1459, 0.4566]]))

## DAY-3

#### Let us now witness the time difference between matmul and the traditional way to multiply tensor

In [176]:
%%time
value1=torch.zeros(3,4)
for x,i in enumerate(debug_tensor):
    # print(i,x)
    for cols in (range(transpose_random_tensor.shape[1])):

        for y,j in enumerate(transpose_random_tensor):
            
                # print(i[y],j[cols])
                value1[x][cols]+=i[y]*j[cols]
                # print(x,cols)
    
value1
    
    

CPU times: total: 0 ns
Wall time: 2 ms


tensor([[1.2175, 0.3244, 0.8567, 1.0780],
        [1.3631, 0.4385, 1.0680, 1.4829],
        [1.1557, 0.3287, 1.0656, 1.0666]])

In [177]:
range(len(debug_tensor))

range(0, 3)

In [178]:
%%time
value2=torch.matmul(debug_tensor,transpose_random_tensor)
value2

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[1.2175, 0.3244, 0.8567, 1.0780],
        [1.3631, 0.4385, 1.0680, 1.4829],
        [1.1557, 0.3287, 1.0656, 1.0666]])

In [164]:
value1==value2

tensor([[ True, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

##### CPU times: total: 0 ns ,Wall time: 2 ms vs CPU times: total: 0 ns, Wall time: 0 ns
##### it is less than nano second which 10^(-9) that is more than million times faster than traditional method

3
4


##### Finding mean, max, mean and sum, etc, This might come in handy if i want to standarazie the data

In [181]:
x=torch.rand(1,100,2)
x

tensor([[[2.3733e-01, 2.1947e-01],
         [6.3051e-01, 7.8455e-01],
         [9.2240e-01, 5.8039e-02],
         [4.1284e-01, 5.2453e-01],
         [8.9033e-01, 8.1376e-01],
         [5.1937e-01, 3.9539e-01],
         [7.9916e-01, 4.5352e-01],
         [1.9563e-01, 2.9965e-02],
         [3.7313e-01, 1.4728e-01],
         [3.4279e-01, 2.9387e-01],
         [4.2301e-01, 9.7636e-01],
         [7.4072e-01, 9.4776e-01],
         [9.7924e-01, 8.6420e-01],
         [4.5430e-01, 1.0378e-01],
         [8.8538e-01, 3.7739e-01],
         [5.3182e-01, 3.1639e-01],
         [7.3721e-01, 2.5382e-01],
         [6.9113e-01, 3.8304e-01],
         [1.1124e-01, 4.4857e-02],
         [3.3754e-01, 8.6627e-01],
         [5.4232e-01, 2.5509e-02],
         [8.5497e-01, 2.5127e-01],
         [3.9120e-01, 8.6583e-01],
         [3.7485e-01, 1.3583e-01],
         [9.8844e-01, 5.9087e-02],
         [6.9905e-01, 2.0960e-02],
         [7.9757e-01, 4.9172e-01],
         [2.4321e-01, 8.7089e-01],
         [9.6044e-01

In [187]:
torch.sum(x), torch.mean(x),torch.min(x)

(tensor(96.8522), tensor(0.4843), tensor(6.0081e-05))

In [192]:
x_int = torch.tensor([1,100],dtype=int)

In [195]:
#NOTE: this won't work because mean only takes float but we are providing int
torch.mean(x_int)

tensor(0.4843)

In [199]:
#After converting to float it should work
torch.mean(x_int.type(torch.float))

tensor(50.5000)

#### Finding the position of the min, max?, use arg___

In [202]:
x_int.argmax(),x_int.argmin()

(tensor(1), tensor(0))

### Reshaping, Stacking, view
- #### Reshaping - reshapes an input tensor to a defined shape,ok? 
- #### View - Return a view of an input tensor of a certain shape but keep the same memory as original tensor
- #### Stacking - Combine multiple tensor on top of each other (vstack) or side by side (hstack)
- #### Squeeze - removes all 1 dimensions from a tensor
- #### Unsqueeze - adds 1 dimensions to a tensor
- #### Permute - Return a view of the input with dimnesions permuted (swapped) in a certain way


In [211]:
x = torch.arange(1,21)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 torch.Size([20]))

In [214]:
# So basically the reshape x,y : x*y=tensor.shape
x_reshaped=x.reshape(4,5)
x_reshaped

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [218]:
#View
z=x.view(1,20) #extra dimension add ? z and x share same memory?
z.shape,x.shape

(torch.Size([1, 20]), torch.Size([20]))

In [219]:
z[:,0]=40

In [225]:
x[0] ## so changing z also makes changes to x

tensor(40)

In [226]:
# Stack
x_stacked=torch.stack([x,x_reshaped,x_int])
x_stacked

RuntimeError: stack expects each tensor to be equal size, but got [20] at entry 0 and [4, 5] at entry 1

#### So every tensor needs to be of equal size

In [232]:
x_stacked=torch.stack([x,x,x,x],dim=0) #0 ma row wise stack hunxa 1 ma col wise i.e side by side
x_stacked, x_stacked.shape

(tensor([[40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20]]),
 torch.Size([4, 20]))

In [238]:
# does not work because it does not have single dimension, unity dimension?
x_stacked.squeeze()
x_stacked,x_stacked.shape

(tensor([[40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20],
         [40,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
          19, 20]]),
 torch.Size([4, 20]))

In [274]:
random_x=torch.zeros(1,10)
random_x,random_x.shape

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), torch.Size([1, 10]))

In [284]:

print(f'before squeeze {random_x.shape}, {random_x}')
x_squeeze=random_x.squeeze(dim=0)
print(f'after squeze {x_squeeze.shape} {random_x}')

before squeeze torch.Size([1, 10]), tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
after squeze torch.Size([1, 10]) tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
