In [48]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [3]:
print(torch.__version__)

2.5.1+cu124


#### Basically creating a tensor, but why are we calling it a scalar?

In [4]:
#scalar
scalar =torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
# so it has 0 dimension , which makes sense
scalar.ndim

0

In [7]:
#getting back int form python data types 
scalar.item()

7

### Vectors

In [8]:
vector=torch.tensor([1,2,3])

In [9]:
vector

tensor([1, 2, 3])

In [10]:
vector.ndim

1

### Matrix

In [11]:
matrix=torch.tensor([[1,2,3],[4,5,6]])

In [12]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
matrix.ndim

2

In [14]:
matrix[0,2]

tensor(3)

### 3D 

In [15]:
tensors=torch.tensor([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [16]:
tensors

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [17]:
tensors.shape

torch.Size([2, 2, 3])

In [18]:
tensors[0,0]

tensor([1, 2, 3])

# Day-2

### Random tensor

Random tensors are important because the way many neural networks learn is they have random tensor at the beginning and then those numbers are updated ,

In [27]:
#create a random tensor of size(4,5)
random_tensor=torch.rand(4,5)

In [28]:
random_tensor

tensor([[0.8908, 0.5729, 0.7447, 0.9818, 0.4492],
        [0.0802, 0.4181, 0.9921, 0.6956, 0.2639],
        [0.5952, 0.7763, 0.6340, 0.9623, 0.6862],
        [0.4577, 0.9241, 0.5703, 0.0579, 0.8832]])

In [32]:
#creating a random image tensor
random_tensor_image=torch.rand(224,224,3) #height , width and color channel
random_tensor_image.ndim

3

In [37]:
#tensors with binary bits
zero_tensor=torch.zeros(4,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
np.dot(zero_tensor,random_tensor)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [40]:
zero_tensor.dtype

torch.float32

In [41]:
random_tensor.dtype

torch.float32

### It seems that the default data type for tensor is float32

#### Creating zeros tensor which has shape of exisiting tensor

In [46]:
zero_like=torch.zeros_like(random_tensor)
zero_like.shape

torch.Size([4, 5])

In [47]:
random_tensor.shape


torch.Size([4, 5])

#### arange , start, stop, step (kind of like python built in range)


In [60]:
one_to_somewhere=torch.arange(1,100,2)
one_to_somewhere

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [61]:
one_to_somewhere=torch.arange(1,100,1/2)
one_to_somewhere


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000, 16.0000, 16.5000,
        17.0000, 17.5000, 18.0000, 18.5000, 19.0000, 19.5000, 20.0000, 20.5000,
        21.0000, 21.5000, 22.0000, 22.5000, 23.0000, 23.5000, 24.0000, 24.5000,
        25.0000, 25.5000, 26.0000, 26.5000, 27.0000, 27.5000, 28.0000, 28.5000,
        29.0000, 29.5000, 30.0000, 30.5000, 31.0000, 31.5000, 32.0000, 32.5000,
        33.0000, 33.5000, 34.0000, 34.5000, 35.0000, 35.5000, 36.0000, 36.5000,
        37.0000, 37.5000, 38.0000, 38.5000, 39.0000, 39.5000, 40.0000, 40.5000,
        41.0000, 41.5000, 42.0000, 42.5000, 43.0000, 43.5000, 44.0000, 44.5000,
        45.0000, 45.5000, 46.0000, 46.5000, 47.0000, 47.5000, 48.0000, 48.5000,
        49.0000, 49.5000, 50.0000, 50.50

#### So basically we can also put fraction in step

#### Tensor datatypes

In [81]:
#default is float32 for rand 
float_32_tensor=torch.arange(1,10,0.5)
float_32_tensor.dtype

torch.float32

In [89]:
int_64_tensor=torch.tensor([1,2,3.5],dtype=int)
int_64_tensor

tensor([1, 2, 3])

#### some more params passed to tensor

In [92]:
float_32_tensor=torch.tensor([3.0,4.0,5.0],
                             dtype=None, # so that we don't have problem doing operation with float 16
                             device="cuda",  # be careful, tensor on cpu and gpu does not mix well
                             requires_grad=False #no track gradient, idk what that means yet
                             ,)
float_32_tensor

tensor([3., 4., 5.], device='cuda:0')

### Conversion of data types

In [96]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

##### let see what happens if we multiply two different float with differnt bit

In [98]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 25.], device='cuda:0')

##### let's multiply float and integer

In [100]:
int_16_tensor=float_16_tensor.type(torch.int16)
int_16_tensor.dtype

torch.int16

In [101]:
int_16_tensor*float_16_tensor

tensor([ 9., 16., 25.], device='cuda:0', dtype=torch.float16)

##### Python allows this

#### Errors I will get in tensor data 
-  ##### Tensor not right data type (find the data type , use tensor.dtype)
-  ##### Tensor not right shape (get shape from tensor, use tensor.shape)
-  ##### Tensor not right device (use tensor.device)


#### see this if you get the above errors

In [108]:
debug_tensor=torch.rand(3,5)

debug_tensor

tensor([[0.2971, 0.9924, 0.0116, 0.6705, 0.4599],
        [0.0082, 0.3939, 0.2686, 0.7952, 0.5678],
        [0.5573, 0.3722, 0.6335, 0.4328, 0.8824]])

In [110]:
print(f'the shape of tensor is {debug_tensor.shape}')
print(f'the datatypes of tensor is {debug_tensor.dtype}')
print(f'the device of tensor is {debug_tensor.device}')


the shape of tensor is torch.Size([3, 5])
the datatypes of tensor is torch.float32
the device of tensor is cpu


#### Manipulating Tensor (tensor operations)

#### 1: Addition (it must have same shape)

In [113]:
debug_tensor+debug_tensor

tensor([[0.5942, 1.9848, 0.0231, 1.3409, 0.9198],
        [0.0165, 0.7877, 0.5372, 1.5904, 1.1356],
        [1.1146, 0.7444, 1.2670, 0.8655, 1.7649]])

In [114]:
debug_tensor +10

tensor([[10.2971, 10.9924, 10.0116, 10.6705, 10.4599],
        [10.0082, 10.3939, 10.2686, 10.7952, 10.5678],
        [10.5573, 10.3722, 10.6335, 10.4328, 10.8824]])

#### 2: Subtraction (It must have same shape)

In [115]:
debug_tensor -10

tensor([[-9.7029, -9.0076, -9.9884, -9.3295, -9.5401],
        [-9.9918, -9.6061, -9.7314, -9.2048, -9.4322],
        [-9.4427, -9.6278, -9.3665, -9.5672, -9.1176]])

In [117]:
debug_tensor - debug_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

#### 3: Multiplication (two tensor must have cols and row same for first and second tensor in order)

In [123]:
debug_tensor.shape, random_tensor.shape

(torch.Size([3, 5]), torch.Size([4, 5]))

In [124]:
## this should not work
debug_tensor*random_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [127]:
transpose_random_tensor=np.transpose(random_tensor)
transpose_random_tensor.shape

torch.Size([5, 4])

In [128]:
## now we should be able to multiply debug tensor with transpose_random_tensor
debug_tensor*transpose_random_tensor

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

### OH NO


In [129]:
debug_tensor.shape,transpose_random_tensor.shape


(torch.Size([3, 5]), torch.Size([5, 4]))

In [132]:
debug_tensor.size(),transpose_random_tensor.size()

(torch.Size([3, 5]), torch.Size([5, 4]))

In [133]:
torch.matmul(debug_tensor,transpose_random_tensor)

tensor([[1.7067, 1.0380, 1.9153, 1.5046],
        [1.4689, 1.1348, 1.6358, 1.0684],
        [2.0028, 1.3627, 2.0443, 1.7647]])